name: Build Clonzy Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK, Build Tools & Platform
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: android-31
          arch: x86_64
          profile: default

      - name: Build debug APK
        working-directory: app
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clonzy-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
