name: Build Signed Clonzy Release APK (No gradlew required)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31
          components: build-tools;31.0.0,platforms;android-31

      - name: Install Gradle (uses gradle/gradle-build-action)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'    # you can change to another version if needed

      - name: Decode keystore
        if: secrets.KEYSTORE_BASE64 != ''
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > clonzy-release.keystore

      - name: Build signed release APK
        run: |
          ./gradlew assembleRelease || gradle assembleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        # Notes: the command tries ./gradlew first (if wrapper exists) then falls back to system gradle

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Clonzy-release-apk
          path: app/build/outputs/apk/release/app-release.apk
